name: SmartEye
description: Real-time IoT surveillance with camera feed, telemetry, alerts, and analytics.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Adjusted for broader compatibility

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0        # WebSocket for real-time communication
  flutter_webrtc: ^0.12.11          # WebRTC for potential live streaming (optional)
  fl_chart: ^0.63.0                # Charts for analytics
  provider: ^6.0.0                 # State management
  flutter_screenutil: ^5.9.0        # Responsive design
  http: ^1.1.0                     # HTTP requests for backend communication
  firebase_messaging: ^14.6.0       # Push notifications
  google_fonts: ^6.1.0             # For Orbitron and RobotoMono fonts
  cached_network_image: ^3.3.1      # Efficient image loading for captured images
  intl: ^0.19.0                    # Date formatting for analytics

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1   # Launcher icon generation

flutter:
  uses-material-design: true
  assets:
    - assets/aii.png
    - assets/ken.jpeg
    - assets/prince.jpeg
    - assets/aprel.jpeg
    - assets/mwegs.jpeg
    - assets/ron.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/sm.png"
  adaptive_icon_background: "#0A0E21"
  adaptive_icon_foreground: "assets/sm.png"